django-ecommerce/api/urls.py
from django.urls import path
from rest_framework.authtoken import views
from .views import ItemList, ItemDetail

urlpatterns = [
    path('api/', ItemList.as_view(), name='api'),
    path('api/detail/<slug>/', ItemDetail.as_view(), name='api_detail'),
    path('api-token-auth/', views.obtain_auth_token, name='api_token')
]

django-ecommerce/core/urls.py
from django import views
from django.urls import path
from .views import (
    AboutView,
    AnalyticsView,
    CabinetView,
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    view_func,
    pay,
    #cabinet,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    CategoryView,
    ItemCreateView,
    ItemUpdateView,
    ItemDeleteView,
    ContactForm, 
    ContactCreate,
    BusinessCreate
    #success

)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('category/<slug>/', CategoryView.as_view(), name='category'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('checkout/pay', pay, name='pay'),

    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path('about/', AboutView.as_view(), name='about'),
    path('personal_cabinet/itemcreate/', ItemCreateView.as_view(), name='itemcreate'),
    path('personal_cabinet/update/<slug>/', ItemUpdateView.as_view(), name='itemupdate'),
    path('personal_cabinet/delete/<slug>/', ItemDeleteView.as_view(), name='itemdelete'),
    path('personal_cabinet/', CabinetView.as_view(), name='cabinet'),
    path('contact/', ContactCreate.as_view(), name='contact'),
    path('personal_cabinet/add_data', BusinessCreate.as_view(), name='business_data'),
    path('personal_cabinet/analytics', view_func, name='analytics'),

    
    
    #path('success/', success, name='success_page'),

]

django-ecommerce/templates/about.html
{% extends "base.html" %}

{% block content %}
  <main>
  <!-- {{ object.second_title }} 
     <h4>{{ object.second_title }}</h4> -->
     <body>
       <div class="container">

        <!-- <div class="col-md-6 text-left"> -->

          <h1 class="my-4 h1">
           О компании
           {{ about.fist_title}}
          </h1>
          
        <div class="text-justify">
          <p>
            Лучший маркетплейс на рынке маркетплейсов, которые реализуют автотовары
          
          </p>
          <h1 class="my-4 h1">
            Миссия
           </h1>
          <p>
            Быть лучшими
          </p>

          <h1 class="my-4 h1">
            Контакты
           </h1>
          <p>
            Москва, Стремянный переулок, 36

          </p>
          <p>
            8 (800) 555-35-35
          </p>
        
  
        </div>
  
          
  
        <!-- </div> -->
        <!-- <p>
          <img src="../media_root/about.jpg" alt="Тачка" class="img-thumbnail">
        </p> -->
  


       </div>
      
    </body>

    
  </main>

{% endblock content %}

django-ecommerce/templates/analytics.html
{% extends "base.html" %}

{% block content %}

{% load googlecharts %}
<div class="container">
	{% load googlecharts %}


	<h1>Количество покупок в день</h1>

	<div id="count_graph"> Количество покупок в день</div>
	<h1>Прибыль в день</h1>

	<div id="sum_graph">Прибыль в день</div>

	
	{% googlecharts %}
		{% data values "count" %}
			{% col "string" "Date" %}"{{ val|date:"M j" }}"{% endcol %}
			{% col "number" "шт" %}{{ val }}{% endcol %}
		{% enddata %}

		{% data values2 "sum" %}
			{% col "string" "Date" %}"{{ val|date:"M j" }}"{% endcol %}
			{% col "number" "Р" %}{{ val }}{% endcol %}
		{% enddata %}
	
		{% options %}
			kind: "LineChart",
			options: {
				backgroundColor: "#f9f9f9",
				colors: ["#09f"],
				gridlineColor: "#ddd",
				legend: "none",
				vAxis: {minValue: 0},
				chartArea: {left: 40, top: 20, width: 550, height: 440},
				width: 600,
				height: 480
			}
		{% endoptions %}
	
		{% graph "count_graph" "count" %} {# используем опции по умолчанию #}
		{% graph "sum_graph" "sum" %} {# используем опции по умолчанию #}
	{% endgooglecharts %}

	
	</div>
</div>

{% endblock content %}

django-ecommerce/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

{% include "navbar.html" %}

<body>

    <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>

    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}

    {% include "footer.html" %}
    {% include "scripts.html" %}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>
</html>

django-ecommerce/templates/business_data.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div class="container">
      <form method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Send message">
    </form>

    </div>
       

  </main>

{% endblock content %}

django-ecommerce/templates/category-page.html
{% extends "base.html" %}

{% block content %}
<main>
  <nav class="navbar navbar-expand-lg navbar-dark primary-color primary mb-5">
    <div class="container">
    <!-- Navbar brand -->
    <span class="navbar-brand">Категории:</span>

    <!-- Collapse button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
      aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Collapsible content -->
    <div class="collapse navbar-collapse" id="basicExampleNav">
      <!-- Links -->
      

      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'core:home' %}">Все
            <span class="sr-only">(current)</span>
          </a>
        </li>
        {% for item in item_categories %}
          {% ifchanged %}
          <li class="nav-item">
            <a class="nav-link" href="{{ item.get_absolute_url }}">{{ item.name }}
              <span class="sr-only">(current)</span>
            </a>
          </li>
          {% endifchanged %}
        {% endfor %}
      </ul>
      <!-- Links -->

      <!--<form class="form-inline">
        <div class="md-form my-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        </div>
      </form>
    </div> -->
    <!-- Collapsible content -->
  </div>
  </nav>
  <div class="container">

    <!--Navbar-->
    
    <!--/.Navbar-->

    <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <div class="row wow fadeIn">

          {% for item in object_list %}
          <div class="col-lg-3 col-md-6 mb-4">

            <div class="card">

              <div class="view overlay">
                {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top"> {% endcomment %}
                <img src="{{ item.image.url }}" class="card-img-top">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

              <div class="card-body text-center">
                <!-- <a href="" class="grey-text">
                  <h5>{{ item.get_category_display }}</h5>
                </a> -->
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                      <!-- <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span> -->
                    </a>
                  </strong>
                </h5>

                <p class="lead">
                  {% if item.discount_price %}
                  <span class="mr-1">
                    <del class="2 text-muted">{{ item.price }}₽</del>
                  </span>
               <big class=" font-weight-bold">{{ item.discount_price }}₽</big>
                  {% else %}
                  <span>{{ item.price }}₽</span>
                  {% endif %}
                </p>
                
                
              </div>
              
              <a href="{{ item.get_add_to_cart_url }}" class="btn btn-primary">
                В корзину
                <i class="fas fa-shopping-cart ml-1"></i>
              </a>
              
            </div>
            
          </div>
          {% endfor %}
        </div>

      </section>
    </div>
 </main>

{% endblock content %}

django-ecommerce/templates/contact.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <main>
  <!-- {{ object.second_title }} 
     <h4>{{ object.second_title }}</h4> -->
     <body>
      <div class="col-md-6 text-left">
       
<!-- <form method="post" class="card-body">
  {% csrf_token %}
  <div class="col-lg-4 col-md-6 mb-4">
    <input type='text' placeholder='Ваше имя' id='first_name' name='first_name' class='form-control' />
   
  </div>

  <div class="col-lg-4 col-md-6 mb-4">
 
    <input type='text' placeholder='Ваша фамилия' id='last_name' name='last_name' class='form-control' />
  
  </div>
  <div class="col-lg-4 col-md-6 mb-4">

    <input type='text' placeholder='Ваша почта' id='email' name='email' class='form-control' />
  
  </div>
  <div class="col-lg-4 col-md-6 mb-4">

    <input type='text' placeholder='Ваш вопрос' id='message' name='message' class='form-control' />
  
  </div>

  <input type="submit">
</form> -->
        

<form method="POST">
  {% csrf_token %}
 
    {{ form.first_name }}
    {{ form.last_name }}
    {{ form.email }}
    {{ form.message }}

    <input type="submit">
</form>



</body>

    
</main>

{% endblock content %}

django-ecommerce/templates/delete_item.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div class="container mt-2 pt-2">


      <form method="post">{% csrf_token %}
        <p>Вы уверены что хотите удалить "{{ object }}"?</p>
            <input type="submit" class="btn btn-primary" value="Да">
            <input type="button" class="btn btn-primary" href="{% url 'core:cabinet' %}" value="Нет">
            <!-- <span class="btn btn-primary btn-md my-0 p"> Нет </span> -->
    </form>

    

    </div>
    

  </main>

{% endblock content %}

django-ecommerce/templates/footer.html
<footer class="page-footer text-center font-small primary mt-10  ">
<div class="container">

  <section class="mt-5 pt-4">
    <p>
      <a href="{% url 'core:about' %}"> О компании </a>
    </p>
    
    <p>
      <a href="{% url 'core:contact' %}"> Поддержка </a>
    </p>
    

  </section>
</div>
    <!--<hr class="my-4">-->
  
    <!-- Social icons -->
    <!-- <div class="pb-4">
      <a href="https://new.rea.ru/#0" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://new.rea.ru/#0" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://new.rea.ru/#0" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>
      
      <a class="nav-link waves-effect" href="{% url 'account_login' %}">
          <i class="clearfix d-none d-sm-inline-block"> О компании </i>
      </a>
  
    </div>--> 
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2022 Copyright:
      <a href="https://new.rea.ru/#0" target="_blank"> Disimoson & Catyukea </a>
    </div>
    <!--/.Copyright-->

</footer>

django-ecommerce/templates/itemform.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div  class="container mt-2 pt-2 "> 
      <form method="post" enctype="multipart/form-data">{% csrf_token %}
        <!-- <input name='{{ form.title }}' class='form-control' />  -->
        <div>
          {{ form.title }}
        </div>

        <div>
          {{ form.price }}
        </div>
       
        <div>
          {{ form.discount_price }}
        </div>
        <div>

          {{ form.categories }}
        </div>
        <div>
          {{ form.slug }}
        </div>
        <div>
          
          {{ form.image }}
          Иконка товара*
        </div>
        <div>
          
          {{ form.image_background }}
          Изображение товара*
        </div>
        <div>
          {{ form.attributes }}
        </div>
        <div>
          {{ form.quantity }}
        </div>
        
        
       

        


        <!-- {{ form.as_p }} -->
        <input type="submit" class="btn btn-primary" value="Создать товар">
    </form>

    </div>
       
 

  </main>

{% endblock content %}

django-ecommerce/templates/navbar.html
{% load cart_template_tags %}

<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar py-3">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="/">
        <strong class="blue-text">Marketplace</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          {% comment %} <li class="nav-item active">
            <a class="nav-link waves-effect" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="/checkout">
            Checkout</a>
          </li> {% endcomment %}
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'core:cabinet' %}">
              <span class="clearfix d-none d-sm-inline-block"> {{request.user}} </span>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
              <i class="fas fa-shopping-cart"></i>
               <!--<span class="clearfix d-none d-sm-inline-block"> Корзина </span>-->
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
              <span class="clearfix d-none d-sm-inline-block"> Выйти </span>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login' %}">
              <span class="clearfix d-none d-sm-inline-block"> Войти </span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
              <span class="clearfix d-none d-sm-inline-block"> Зарегистрироваться </span>
            </a>
          </li>
          {% endif %}
        </ul>
      </div>

    </div>
  </nav>

django-ecommerce/templates/order_summary.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div class="container">

    <div class="table-responsive text-nowrap">
    <h2>Корзина</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Название товара</th>
            <th scope="col">Цена</th>
            <th scope="col">Количество</th>
            <th scope="col">Цена</th>
        </tr>
        </thead>
        <tbody>
        {% for order_item in object.items.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.item.title }}</td>
            <td>{{ order_item.item.price }}</td>
            <td>
                <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                {{ order_item.quantity }}
                <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
            </td>
            <td>
            {% if order_item.item.discount_price %}
                {{ order_item.get_total_discount_item_price }} ₽
                <span class="badge badge-primary">Saving {{ order_item.get_amount_saved }} ₽</span>
            {% else %}
                {{ order_item.get_total_item_price }} ₽
            {% endif %}
            <a style='color: red;' href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                <i class="fas fa-trash float-right"></i>
            </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan='5'>Ваша корзина пуста</td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-link float-right' href='/'>Продолжить покупки</a>
            </td>
        </tr>
        {% endfor %}
        {% if object.coupon %}
        <tr>
            <td colspan="4"><b>Купон</b></td>
            <td><b>-₽{{ object.coupon.amount }}</b></td>
        </tr>
        {% endif %}
        {% if object.get_total %}
        <tr>
            <td colspan="4"><b>Итого</b></td>
            <td><b>{{ object.get_total }} ₽</b></td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-warning float-right ml-2' href='/checkout/'>Оплатить</a>
            <a class='btn btn-link float-right' href='/'>Продолжить покупки</a>
            </td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    </div>

    </div>
  </main>

{% endblock content %}

django-ecommerce/templates/request_refund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <main>
    <div class="container">

    <h2>Запросить возврат</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-primary'>Отправить</button>
    </form>

    </div>
  </main>

{% endblock content %}

django-ecommerce/templates/scripts.html
{% load static %}
  
<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
  new WOW().init();

</script>

django-ecommerce/templates/update_item.html
{% extends "base.html" %}

{% block content %}
  <main>
        <form method="post" enctype="multipart/form-data">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Update">
        </form>

  </main>

{% endblock content %}